/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { ProposalScorer } from "./ProposalScorer";
export * as factories from "./factories";
export { ProposalScorer__factory } from "./factories/ProposalScorer__factory";
